spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
      hibernate.query.in_clause_parameter_padding: true
    open-in-view: false
  datasource:
    hikari:
      auto-commit: false

---
spring:
  profiles: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/income-bot;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console.settings.trace: false
    console:
      enabled: true
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
---
spring:
  profiles: real

  datasource:
    hikari:
      username: jojoldu
      driver-class-name: org.mariadb.jdbc.Driver
      idleTimeout: 600000      #10m
      maxLifetime: 1800000     #30m
      minimumIdle: 4
      maximumPoolSize: 15
      data-source-properties:
        connect-timeout: 30000
        socket-timeout: 60000

