spring:
  profiles:
    include:
      - core
      - bot
    active: local
  batch.job.names: ${job.name:NONE}

logging.level:
      org:
        hibernate.SQL: debug
        springframework:
          batch:
            item:
              querydsl.reader: DEBUG
              database.JpaItemWriter: debug
---
spring:
  profiles: local

---
spring:
  profiles: local-real
  profiles.include:
      - real-test
---
spring:
  profiles: real

  datasource:
    hikari:
      maximumPoolSize: 5